### ISSUE TITLE
[Mac Calculator method issue]

### ISSUE THREAD

**Issue by MoAdelAbdelrahman** [imohsenb/ISO8583-Message-Client-DotNet#5]
Greetings,

I've installed the library, however, when building an ISO message, here's what my ide tells me:
--The Name MacCalculator doesn't exist in the current context--
I've ran through the files trying to find the method but I found no solutions. 

Appreciate your feedback

**Comment by imohsenb** [comment]
Hi, 

You can find two different MAC generators inside the [crypto](https://github.com/imohsenb/ISO8583-Message-Client-DotNet/tree/master/imohsenb.iso8583/crypto) folder and as an example, you can find some test cases for MAC generators [here](https://github.com/imohsenb/ISO8583-Message-Client-DotNet/blob/master/Iso8583Test/MacGeneratorUnitTest.cs).
